import {normalizeIndent,parseHtml,portableHtml} from './document.js';
import {prepareRichSourceHighlight} from './source-highlighting.js';
import {captureTemplate,parseTemplate,templateJson} from './templates.js';
import {renderPng,outputBounds,move,id} from './annotation-model.js';
import {request} from './bridge.js';

export async function run(){
  const results=[];const check=(value,name)=>{if(!value)throw Error(name);results.push(name);};
  const delay=ms=>new Promise(resolve=>setTimeout(resolve,ms));
  const doc=()=>document.querySelector('#document').contentDocument;
  const selectText=(selector)=>{const range=doc().createRange();range.selectNodeContents(doc().querySelector(selector));const s=doc().getSelection();s.removeAllRanges();s.addRange(range);doc().dispatchEvent(new Event('selectionchange'));};
  const click=selector=>{const element=document.querySelector(selector);if(!element)throw Error('Missing control: '+selector);element.click();};
  const waitFor=async selector=>{for(let i=0;i<100;i++){const el=document.querySelector(selector);if(el)return el;await delay(50);}throw Error('Timed out: '+selector);};
  await window.editor.ready();
  check(doc().body.isContentEditable,'Visual HTML is editable');
  const savedCaret=doc().createRange();savedCaret.setStart(doc().querySelector('p').firstChild,7);savedCaret.collapse(true);
  doc().getSelection().removeAllRanges();doc().getSelection().addRange(savedCaret);doc().dispatchEvent(new Event('selectionchange'));
  await window.editor.setBase(doc().baseURI);
  check(doc().getSelection().anchorNode===doc().querySelector('p').firstChild&&doc().getSelection().anchorOffset===7,'Refreshing the saved asset folder preserves the text insertion point');
  selectText('p');document.querySelector('#fontSize').value='28';document.querySelector('#fontSize').dispatchEvent(new Event('change'));
  check(doc().querySelector('p').innerHTML.includes('28px'),'Font size control applies the requested pixel size');
  selectText('p');window.editor.command('bold');check(/font-weight: bold|<b>|<strong>/.test(window.editor.html()),'Bold applies to selected text');
  window.editor.command('italic');window.editor.command('underline');window.editor.command('strikeThrough');
  window.editor.command('foreColor','#c22c44');window.editor.command('hiliteColor','#fff2a6');
  check(window.editor.html().includes('text-decoration')&&window.editor.html().includes('rgb(194, 44, 68)'),'Text decoration and selection colors persist');
  selectText('p');document.querySelector('#fontSize').value='22';document.querySelector('#fontSize').dispatchEvent(new Event('change'));
  check(doc().querySelector('p').innerHTML.includes('22px'),'Font size can change after other rich-text formatting');
  check(normalizeIndent('    if (ready) {\n        run();\n    }')==='if (ready) {\n    run();\n}','Code indentation preserves internal alignment');
  for(const language of ['csharp','html','javascript','css','tsql'])check(prepareRichSourceHighlight(language==='html'?'<div>Hello</div>':'SELECT const public color 123 "hello"',language).highlighted,'PMT highlighting supports '+language);
  const range=doc().createRange();range.selectNodeContents(doc().body);range.collapse(false);doc().getSelection().removeAllRanges();doc().getSelection().addRange(range);doc().dispatchEvent(new Event('selectionchange'));
  const insert=window.editor.pasteCode();await waitFor('dialog textarea[name=code]');document.querySelector('[name=code]').value='    const greeting = "Hello";\n    console.log(greeting);';document.querySelector('[name=language]').value='javascript';click('dialog button[value=ok]');await insert;
  check(doc().querySelector('pre[data-sin-code=javascript] .rich-source-token-keyword'),'Paste Code produces highlighted editable blocks');
  const edit=window.editor.pasteCode(doc().querySelector('pre[data-sin-code]'));await waitFor('dialog textarea[name=code]');document.querySelector('[name=code]').value='    SELECT Id\n    FROM Prompts;';document.querySelector('[name=language]').value='tsql';click('dialog button[value=ok]');await edit;
  check(doc().querySelector('pre[data-sin-code=tsql]')?.textContent==='SELECT Id\nFROM Prompts;','Code language and text can be edited again');
  const canvas=document.createElement('canvas');canvas.width=360;canvas.height=200;const ctx=canvas.getContext('2d');ctx.fillStyle='#dce9f8';ctx.fillRect(0,0,360,200);ctx.fillStyle='#145c96';ctx.font='bold 30px Segoe UI';ctx.fillText('Prompt canvas',25,70);ctx.font='18px Segoe UI';ctx.fillText('Images + editable annotations',25,110);const png=canvas.toDataURL('image/png');
  const insertion=window.editor.insertImage(png);await waitFor('dialog button[value=separate]');click('dialog button[value=separate]');await insertion;
  const image=doc().querySelector('img');check(image&&image.getAttribute('src').includes('/image-'),'Image storage dialog creates separate PNG reference');
  await image.decode();check(image.naturalWidth===360,'Separate PNG is visible immediately after saving the prompt');
  image.click();document.querySelector('#imageWidth').value='220';document.querySelector('#imageWidth').dispatchEvent(new Event('change'));
  check(doc().querySelector('img').style.width==='220px','Image width control resizes selected image');
  window.editor.command('undo');check(doc().querySelector('img').style.width!=='220px','Image resize is undoable');
  const dialogRun=window.editor.openAnnotation(doc().querySelector('img'));await waitFor('dialog.annotation');
  const pointer=async(type,x,y)=>request('test-mouse',{parameters:{type,x,y,button:type==='mouseMoved'?'none':'left',buttons:type==='mouseReleased'?0:1,clickCount:1}});
  const canvasPoint=(x,y)=>{const matrix=document.querySelector('#canvas').getScreenCTM();return new DOMPoint(x,y).matrixTransform(matrix);};
  const drag=async(from,to)=>{await pointer('mousePressed',from.x,from.y);await pointer('mouseMoved',to.x,to.y);await pointer('mouseReleased',to.x,to.y);};
  const imageWidth=()=>document.querySelector('#canvas image').getBoundingClientRect().width;
  const initialImageWidth=imageWidth();
  for(const [x,y] of [[-180,-100],[180,-100],[180,100],[-180,100]]){
    const imageRect=document.querySelector('#canvas image').getBoundingClientRect();
    const center={x:imageRect.x+imageRect.width/2,y:imageRect.y+imageRect.height/2};
    await drag(center,{x:center.x+x,y:center.y+y});await delay(50);
    check(Math.abs(imageWidth()-initialImageWidth)<1,'Moving image toward corner '+x+','+y+' preserves its displayed size');
    check(Number(document.querySelector('[data-geometry=width]').value)===360&&Number(document.querySelector('[data-geometry=height]').value)===200,'Moving image preserves its pixel dimensions');
    click('[data-action=undo]');
  }
  click('[data-tool=arrow]');await drag(canvasPoint(50,150),canvasPoint(430,75));
  check(document.querySelectorAll('[data-layer]').length===2,'Dragging draws an arrow on a separate layer');
  const endpoint=document.querySelector('[data-end="2"]');const endRect=endpoint.getBoundingClientRect();
  await drag({x:endRect.x+endRect.width/2,y:endRect.y+endRect.height/2},canvasPoint(470,90));
  check(Math.abs(Number(document.querySelector('[data-endpoint=x2]').value)-470)<2,'Dragging arrow endpoint moves its target independently');
  click('[data-tool=rectangle]');await drag(canvasPoint(30,125),canvasPoint(200,180));
  check(document.querySelectorAll('[data-layer]').length===3,'Dragging draws a resizable rectangle');
  const handle=document.querySelector('[data-handle=se]');const handleRect=handle.getBoundingClientRect();
  await drag({x:handleRect.x+handleRect.width/2,y:handleRect.y+handleRect.height/2},canvasPoint(240,195));
  check(Number(document.querySelector('[data-geometry=width]').value)>200,'Dragging rectangle handle resizes the object');
  click('[data-tool=circle]');await drag(canvasPoint(255,20),canvasPoint(320,80));
  const stroke=document.querySelector('#noStroke');stroke.checked=true;stroke.dispatchEvent(new Event('change',{bubbles:true}));
  const fill=document.querySelector('#noFill');fill.checked=false;fill.dispatchEvent(new Event('change',{bubbles:true}));
  check(document.querySelectorAll('[data-layer]').length===4,'Circle drawing and transparent outline controls work');
  click('[data-tool=line]');await drag(canvasPoint(10,190),canvasPoint(200,210));
  check(document.querySelector('[data-end="1"]'),'Line exposes independently draggable endpoints');
  click('[data-action=undo]');check(document.querySelectorAll('[data-layer]').length===4,'Annotation undo removes the last drawing');
  click('[data-action=redo]');check(document.querySelectorAll('[data-layer]').length===5,'Annotation redo restores the drawing');
  const original=[...document.querySelectorAll('[data-layer]')].find(el=>el.textContent.includes('Original image'));original.click();
  const crop=document.querySelector('[data-crop-value=left]');crop.value='20';crop.dispatchEvent(new Event('change',{bubbles:true}));
  const radius=document.querySelector('[data-radius=topLeft]');radius.value='16';radius.dispatchEvent(new Event('change',{bubbles:true}));
  click('[data-action=crop]');const cropHandle=document.querySelector('[data-crop=e]'),cropRect=cropHandle.getBoundingClientRect();
  await drag({x:cropRect.x+cropRect.width/2,y:cropRect.y+cropRect.height/2},canvasPoint(340,100));
  check(Number(document.querySelector('[data-crop-value=right]').value)>=19,'Dragging crop handle changes the precise crop value');
  await request('test-capture');
  click('[data-action=saveTemplate]');await waitFor('dialog.form-dialog [name=name]');document.querySelector('dialog.form-dialog [name=name]').value='Reusable cropped image';click('dialog.form-dialog button[value=ok]');await delay(100);
  check(document.querySelector('[data-template]'),'Object template appears in library');
  const templateData=(await request('templates-load'))[0];const imported=await parseTemplate(templateJson(templateData));check(imported.objects[0].type==='embedded-image','PMT image template JSON round-trips');
  click('[data-action=apply]');await dialogRun;
  const annotated=doc().querySelector('img[data-sin-annotation]');check(annotated,'Annotation apply retains layer metadata');
  const state=JSON.parse(annotated.dataset.sinAnnotation);check(state.objects[0].imageClip.x===20&&state.objects[0].cropCornerRadii.topLeft===16,'Numeric crop and per-corner radius retained non-destructively');
  state.objects.push({id:id(),type:'arrow',x1:60,y1:160,x2:410,y2:80,stroke:'#d53139',strokeWidth:5,arrowSize:22,opacity:1,visible:true});
  const before=outputBounds(state);move(state.objects[1],100,0);check(outputBounds(state).width>before.width,'Annotations outside image expand output width');
  const template=captureTemplate(state.objects,'Image and arrow');const roundtrip=await parseTemplate(templateJson(template));check(roundtrip.objects.length===state.objects.length&&roundtrip.objects.some(o=>o.type==='arrow'),'PMT image and shape template exchange retains all objects');
  state.objects.push({id:id(),type:'rectangle',x:30,y:130,width:190,height:45,stroke:'#246bac',strokeWidth:3,fill:'none',opacity:1,visible:true});
  const rendered=await renderPng(state);annotated.src=rendered.data;annotated.dataset.sinAnnotation=JSON.stringify(state);annotated.dataset.sinStorage='inline';doc().body.dispatchEvent(new Event('input',{bubbles:true}));
  const exported=await portableHtml(window.editor.html(),'https://sin-document.local/');const parsed=parseHtml(exported);check([...parsed.images].every(i=>i.src.startsWith('data:image/png;base64,')),'Standalone HTML embeds every image as PNG');
  check(!exported.includes('data-sin-runtime')&&!exported.includes('data-sin-selected'),'Runtime selection and editor styles are excluded from saved HTML');
  const stored=window.editor.html();await window.editor.load('<html><head><title>Keep title</title></head><body><script>parent.document.body.dataset.unsafe="yes"</script><p onclick="parent.document.body.dataset.unsafe=\'yes\'">Scripts stay inert</p></body></html>');await delay(50);doc().querySelector('p').click();check(!document.body.dataset.unsafe,'Document scripts and event handlers cannot run in editor');check(window.editor.html().includes('Keep title')&&window.editor.html().includes('<script>'),'Source round-trip preserves document head and script text');
  await window.editor.load(stored);await window.editor.ready();
  const blank=window.editor.openAnnotation();await waitFor('dialog button[value=inline]');click('dialog button[value=inline]');await waitFor('dialog.annotation');
  check(document.querySelectorAll('[data-layer]').length===0,'Insert an Image opens a blank drawing canvas');
  const imageBlob=await (await fetch(png)).blob();
  async function pasteCanvasImage(name){const transfer=new DataTransfer();transfer.items.add(new File([imageBlob],name,{type:'image/png'}));document.querySelector('dialog.annotation').dispatchEvent(new ClipboardEvent('paste',{clipboardData:transfer,bubbles:true,cancelable:true}));}
  await pasteCanvasImage('First.png');for(let i=0;i<100&&document.querySelectorAll('[data-layer]').length<1;i++)await delay(20);
  await pasteCanvasImage('Second.png');for(let i=0;i<100&&document.querySelectorAll('[data-layer]').length<2;i++)await delay(20);
  check(document.querySelectorAll('[data-layer]').length===2,'Pasting multiple images creates independent canvas layers');
  check(Number(document.querySelector('[data-geometry=x]').value)>360,'Second pasted image expands the virtual canvas');
  click('[data-action=apply]');await blank;
  check(doc().querySelectorAll('img[data-sin-annotation]').length===2,'Blank canvas with multiple images inserts into the HTML document');
  const latest=doc().querySelectorAll('img[data-sin-annotation]')[1];const originalWidth=latest.style.width;
  const reopen=window.editor.openAnnotation(latest);await waitFor('dialog.annotation');
  check(document.querySelectorAll('[data-layer]').length===2,'Reopening annotation restores every image layer');
  click('[data-action=apply]');await reopen;
  check(doc().querySelectorAll('img[data-sin-annotation]')[1].style.width===originalWidth,'Annotation apply preserves document display width like PMT');
  const savedHtml=window.editor.html();
  await window.editor.load('<p id="typing">Typing:</p>');
  const largeImage=doc().createElement('img');largeImage.src=png;
  largeImage.dataset.sinAnnotation=JSON.stringify({version:1,width:360,height:200,objects:Array.from({length:200},()=>({id:id(),type:'embedded-image',x:0,y:0,width:360,height:200,source:png}))});
  doc().body.append(largeImage);selectText('#typing');doc().getSelection().collapseToEnd();doc().body.focus();
  const root=doc().documentElement,originalClone=root.cloneNode;let snapshots=0;
  root.cloneNode=function(...args){snapshots++;return originalClone.apply(this,args);};
  const timings=[];
  try{
    for(const letter of 'responsive typing'){
      const start=performance.now();doc().execCommand('insertText',false,letter);timings.push(performance.now()-start);await delay(15);
    }
    check(snapshots===0,'Typing in a document with 2 MB of image metadata avoids full HTML snapshots on each key');
    const typed=parseHtml(window.editor.html()).querySelector('#typing').textContent.replace(/\u00a0/g,' ');
    check(typed==='Typing:responsive typing','Immediate save reads the latest text before the deferred update');
    const beforeIdle=snapshots;await delay(250);
    check(snapshots===beforeIdle+1,'A typing burst synchronizes one HTML snapshot after the user pauses');
    results.push('Typing input handling: maximum '+Math.max(...timings).toFixed(1)+' ms per character with '+(largeImage.dataset.sinAnnotation.length/1048576).toFixed(1)+' MB of image metadata');
  }finally{delete root.cloneNode;await window.editor.load(savedHtml);doc().body.dispatchEvent(new Event('input',{bubbles:true}));}
  return results;
}
